config/routes.rb
Rails.application.routes.draw do
  resources :carers
  root to: 'home#index'
  get 'users/login', controller: 'users#login'
  post 'users/auth', controller: 'users#auth'
  post 'users/logout', controller: 'users#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carer.rb
class Carer < JsonApiResource
end

app/models/json_api_resource.rb
class JsonApiResource < JsonApiClient::Resource
  self.site = 'https://vida-core-development.herokuapp.com/api'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_authenitcate
    redirect_to users_login_path if session[:user].nil?
  end

  def credientials
    headers = {}
    headers['X-USER-TOKEN'] = session[:user]['token']
    headers['X-USER-EMAIL'] = session[:user]['key']
    headers
  end
end

app/controllers/carers_controller.rb
class CarersController < ApplicationController

  def index
    Carer.with_headers(credientials) do
      @carers = Carer.all
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :user_authenitcate
  
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'rest-client'
  require 'json'

  def login
  end

  def logout
    api_request 'delete', nil
    session[:user] = nil
    redirect_to users_login_path
  end

  def auth
    request = api_request 'post', api_user: user_params.to_h
    session[:user] = ActiveModelSerializers::Deserialization.jsonapi_parse(request)
    redirect_to root_path
  end



  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def api_request(action, payload)
    url = '{{url}}'
    headers = {}
    headers['content_type'] = :json
    headers['accept'] = :json
    unless session[:user].nil?
      headers['X-USER-TOKEN'] = session[:user]['token']
      headers['X-USER-EMAIL'] = session[:user]['key']
    end
    case action
    when 'post'
      response = RestClient.post url, payload.to_json, content_type: :json, headers: headers
    when 'delete'
      response = RestClient.delete url, {content_type: :json, 'X-USER-TOKEN': session[:user]['token'], 'X-USER-EMAIL': session[:user]['key'] }
    end
    if response.body != ""
      JSON.parse response
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carers_helper.rb
module CarersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => "#"} Ant Grimmitt Code Test
  %button.navbar-toggler{'aria-controls': 'navbarSupportedContent', 'aria-expanded': false, 'aria-label': 'Toggle navigation', data: {target: '#navbarSupportedContent', toggle: 'collapse'}}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "/"}
          Home
          %span.sr-only (current)
      %li.nav-item
        = link_to 'View Carers', carers_path, class: 'nav-link'
    = form_tag users_logout_path, class: ' form-inline my-2 my-lg-0' do
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Logout

app/views/carers/index.html.haml
.row
  .col-md-12.p-4
    .page-header
      %h1 View Carers
    %table.table.table-striped
      %tr
        %th
          Name
        %th
          Email
        %th
          Telephone
      - @carers.each do |carer|
        %tr
          %td
            = carer['first-name']
            = carer['last-name']
          %td
            = carer.email
          %td
            = carer['primary-phone']

app/views/home/index.html.haml
%h1 hello

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ant Grimmitt Code Test
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if session[:user]
      = render partial: 'header'
    = yield

app/views/users/login.html.haml
.login-wrap
  .login-container
    .box
      %header.box-header
        %h3 login
      .box-body.login-form-1
        = form_tag users_auth_path do
          .login-form-main-message
          .main-login-form
            .login-group
              .form-group
                .input-group
                  %span.input-group-addon
                    Email
                  = text_field :user, :email
              .form-group
                .input-group
                  %span.input-group-addon
                    Password
                  = password_field :user, :password
              .form-group
                %button.btn.btn-lg.btn-primary{:type => "submit"}
                  Login